language: node_js
node_js:
  - "stable"

env:
  - NODE_ENV=development

before_install:
  - npm i -g codecov

install:
  - npm install

script:
  - npm test
  - codecov
  - npm run build

notifications:
  email: false